name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - 1.x
      - 2.x
      - 3.x
      - ci/github-action-cypress


jobs:
  
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install dependency
        run: yarn

      - name: Install examples dependency
        run: yarn examples:install

      - name: Run cypress test
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: yarn examples:start
          wait-on: 'http://localhost:7100,http://localhost:7101,http://localhost:7102,http://localhost:7103,http://localhost:7104,http://localhost:7105,http://localhost:7099'
          wait-on-timeout: 6000
          parallel: true
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


