name: Playwright Tests

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - 1.x
      - test/playwright-e2e

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn examples:install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start examples
      run: yarn examples:start
      
    - name: Wait fro 1 minutes
      run: sleep 60

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
