name: Playwright Tests
on:
  pull_request:
  push:
    branches:
      - master
      - next
      - 1.x
      - test/playwright-e2e

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: yarn
    - name: Install examples dependencies
      run: yarn examples:install 
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start examples
      run: yarn examples:start
    - name: Wait for 1 minutes
      run: sleep 60
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30